### ISSUE TITLE
Check config hangs with gasprices_dk enabled

### ISSUE THREAD

**Issue by andrioid** [J-Lindvig/Gasprices_DK#2]
With the following config (copied from the readme), the config check hangs. Latest version.

- Installed via HACS, custom repo
- Enabled through HACS after restart
- Configuration changed and checked afterwards

```
gasprices_dk:

  # OPTIONAL
  # Specify the companies you wish to track
  # Possible values are: ok, goon, circlek, shell, q8, f24, oil & ingo
  # If no companies is specified, we will get every company
  companies:
    - ok
    - ingo
    - circlek

  # OPTIONAL
  # Specify the gas types you wish to track
  # Possible values are: oktan 95 & diesel
  # If no gastype is specified, we will get every gastype
  gas:
    - oktan 95
```
